<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!DOCTYPE mast[
<!ELEMENT mast (model, alphabet, motifs, sequences, runtime)>
<!ATTLIST mast version CDATA #REQUIRED release CDATA #REQUIRED>
<!ELEMENT model (command_line, max_correlation, remove_correlated, strand_handling, translate_dna, max_seq_evalue,
    adj_hit_pvalue, max_hit_pvalue, max_weak_pvalue, host, when)>
<!ELEMENT command_line (#PCDATA)>
<!ELEMENT max_correlation (#PCDATA)>
<!ELEMENT remove_correlated EMPTY>
<!ATTLIST remove_correlated value (y|n) #REQUIRED>
<!ELEMENT strand_handling EMPTY>
<!ATTLIST strand_handling value (combine|separate|norc|protein) #REQUIRED>
<!ELEMENT translate_dna EMPTY>
<!ATTLIST translate_dna value (y|n) #REQUIRED>
<!ELEMENT max_seq_evalue (#PCDATA)>
<!ELEMENT adj_hit_pvalue EMPTY>
<!ATTLIST adj_hit_pvalue value (y|n) #REQUIRED>
<!ELEMENT max_hit_pvalue (#PCDATA)>
<!ELEMENT max_weak_pvalue (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT when (#PCDATA)>
<!ELEMENT alphabet (letter+)>
<!ATTLIST alphabet type (amino-acid|nucleotide) #REQUIRED bg_source (preset|file|sequence_composition) #REQUIRED bg_file CDATA #IMPLIED>
<!ELEMENT letter EMPTY>
<!ATTLIST letter symbol CDATA #REQUIRED ambig (y|n) "n" bg_value CDATA #IMPLIED>
<!ELEMENT motifs (motif+,correlation*,nos*)>
<!ATTLIST motifs source CDATA #REQUIRED name CDATA #REQUIRED last_mod_date CDATA #REQUIRED>
<!ELEMENT motif EMPTY>
<!-- num is simply the loading order of the motif, it's superfluous but makes things easier for XSLT -->
<!ATTLIST motif id ID #REQUIRED num CDATA #REQUIRED name CDATA #REQUIRED width CDATA #REQUIRED
   best_f CDATA #REQUIRED best_r CDATA #IMPLIED bad (y|n) "n">
<!-- for n > 1 motifs there should be (n * (n - 1)) / 2 correlations, obviously there are none for only 1 motif -->
<!ELEMENT correlation EMPTY>
<!ATTLIST correlation motif_a IDREF #REQUIRED motif_b IDREF #REQUIRED value CDATA #REQUIRED>
<!-- nos: Nominal Order and Spacing diagram, a rarely used feature where mast can adjust pvalues for an expected motif spacing -->
<!ELEMENT nos (expect+)>
<!-- length is in the same unit as the motifs, which is not always the same unit as the sequence -->
<!ATTLIST nos length CDATA #REQUIRED>
<!-- the expect tags are expected to be ordered by pos ascending -->
<!ELEMENT expect EMPTY>
<!ATTLIST expect pos CDATA #REQUIRED gap CDATA #REQUIRED motif IDREF #REQUIRED>
<!ELEMENT sequences (database+, sequence*)>
<!-- the database tags are expected to be ordered in file specification order -->
<!ELEMENT database EMPTY>
<!ATTLIST database id ID #REQUIRED num CDATA #REQUIRED source CDATA #REQUIRED name CDATA #REQUIRED last_mod_date CDATA #REQUIRED 
    seq_count CDATA #REQUIRED residue_count CDATA #REQUIRED type (amino-acid|nucleotide) #REQUIRED link CDATA #IMPLIED>
<!-- the sequence tags are expected to be ordered by best combined p-value (of contained score tags) ascending -->
<!ELEMENT sequence (score+,seg*)>
<!ATTLIST sequence id ID #REQUIRED db IDREF #REQUIRED num CDATA #REQUIRED name CDATA #REQUIRED comment CDATA "" length CDATA #REQUIRED>
<!ELEMENT score EMPTY>
<!-- frame is the starting offset for translation of dna sequences which gives the lowest pvalues for the provided protein motifs -->
<!ATTLIST score strand (both|forward|reverse) #REQUIRED frame (a|b|c) #IMPLIED combined_pvalue CDATA #REQUIRED evalue CDATA #REQUIRED>
<!-- within each sequence the seg tags are expected to be ordered by start ascending -->
<!ELEMENT seg (data,hit+)>
<!ATTLIST seg start CDATA #REQUIRED>
<!ELEMENT data (#PCDATA)>
<!-- within each seg the hit tags are expected to be ordered by pos ascending and then forward strand first -->
<!ELEMENT hit EMPTY>
<!-- gap, while superfluous, makes creating motif diagrams for the text version much easier when using XSLT -->
<!ATTLIST hit pos CDATA #REQUIRED gap CDATA #REQUIRED motif IDREF #REQUIRED pvalue CDATA #REQUIRED strand (forward|reverse) "forward" 
    match CDATA #REQUIRED translation CDATA #IMPLIED>
<!ELEMENT runtime EMPTY>
<!ATTLIST runtime cycles CDATA #REQUIRED seconds CDATA #REQUIRED>
]>
<mast version="4.6.1" release="Mon Mar 21 15:08:38 EST 2011">
	<model>
		<command_line>mast /Users/okoro103/workspace/ModuleInducer/tmp/mi_1314733809249/mi_MemeOut1314733809251/dreme_out.motifs /Users/okoro103/workspace/ModuleInducer/tmp/mi_1314733809249/mi_MemeOut1314733809251/memeSeqPos.fa -o /Users/okoro103/workspace/ModuleInducer/tmp/mi_1314733809249/mi_MemeOut1314733809251/mastTestDir1314733840564</command_line>
		<max_correlation>0.60</max_correlation>
		<remove_correlated value="n"/>
		<strand_handling value="combine"/>
		<translate_dna value="n"/>
		<max_seq_evalue>10</max_seq_evalue>
		<adj_hit_pvalue value="n"/>
		<max_hit_pvalue>0.0001</max_hit_pvalue>
		<max_weak_pvalue>0.0001</max_weak_pvalue>
		<host>affix.local</host>
		<when>Tue Aug 30 15:50:40 2011</when>
	</model>
	<alphabet type="nucleotide" bg_source="preset">
		<letter symbol="A" bg_value="0.274"/>
		<letter symbol="C" bg_value="0.225"/>
		<letter symbol="G" bg_value="0.225"/>
		<letter symbol="T" bg_value="0.274"/>
	</alphabet>
	<motifs source="/Users/okoro103/workspace/ModuleInducer/tmp/mi_1314733809249/mi_MemeOut1314733809251/dreme_out.motifs" name="/Users/okoro103/workspace/ModuleInducer/tmp/mi_1314733809249/mi_MemeOut1314733809251/dreme_out.motifs" last_mod_date="Tue Aug 30 15:50:40 2011">
		<motif id="motif_1" num="1" name="TTATCW" width="6" best_f="TTATCT" best_r="AGATAA"/>
		<motif id="motif_2" num="2" name="AACCACAR" width="8" best_f="AACCACAG" best_r="CTGTGGTT"/>
		<motif id="motif_3" num="3" name="CAKCTGY" width="7" best_f="CAGCTGC" best_r="GCAGCTG"/>
		<motif id="motif_4" num="4" name="GTGGGKA" width="7" best_f="GTGGGGA" best_r="TCCCCAC"/>
		<motif id="motif_5" num="5" name="ACYTCCT" width="7" best_f="ACTTCCT" best_r="AGGAAGT"/>
		<correlation motif_a="motif_1" motif_b="motif_2" value="0.25"/>
		<correlation motif_a="motif_1" motif_b="motif_3" value="0.49"/>
		<correlation motif_a="motif_2" motif_b="motif_3" value="0.27"/>
		<correlation motif_a="motif_1" motif_b="motif_4" value="0.19"/>
		<correlation motif_a="motif_2" motif_b="motif_4" value="0.14"/>
		<correlation motif_a="motif_3" motif_b="motif_4" value="0.24"/>
		<correlation motif_a="motif_1" motif_b="motif_5" value="0.26"/>
		<correlation motif_a="motif_2" motif_b="motif_5" value="0.27"/>
		<correlation motif_a="motif_3" motif_b="motif_5" value="0.28"/>
		<correlation motif_a="motif_4" motif_b="motif_5" value="0.14"/>
	</motifs>
	<sequences>
		<database id="db_1" num="1" source="/Users/okoro103/workspace/ModuleInducer/tmp/mi_1314733809249/mi_MemeOut1314733809251/memeSeqPos.fa" name="/Users/okoro103/workspace/ModuleInducer/tmp/mi_1314733809249/mi_MemeOut1314733809251/memeSeqPos.fa" last_mod_date="Tue Aug 30 15:50:09 2011" seq_count="150" residue_count="54133" type="nucleotide"/>
		<sequence id="seq_1_76" db="db_1" num="76" name="jur_76" comment="" length="424">
			<score strand="both" combined_pvalue="1.55e-03" evalue="0.23"/>
			<seg start="76">
				<data>
AGAGGCCTCAGGAGACAGTAAACCTGCCTATACCTTGATCTTAGACTTCCTGCCGCCAGAACTGTGGGAAATAAA
				</data>
				<hit pos="120" gap="119" motif="motif_5" pvalue="6.5e-05" strand="forward" match="+++++++"/>
			</seg>
			<seg start="151">
				<data>
TGTCTGTGGTGGAAGCCCCCCAGTCTGTGGTTGCTTTTTGTTGCTGTTGTGATGGCAGCTGGAGCAGACTGACAC
				</data>
				<hit pos="175" gap="48" motif="motif_2" pvalue="1.5e-05" strand="reverse" match="++++++++"/>
				<hit pos="205" gap="22" motif="motif_3" pvalue="4.4e-05" strand="reverse" match="+++++++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_35" db="db_1" num="35" name="jur_35" comment="" length="202">
			<score strand="both" combined_pvalue="1.56e-03" evalue="0.23"/>
			<seg start="76">
				<data>
GAGGTAGGGGAAGCAGCTGGAGTTGGGAGATAGGAGGCTGAGGCAGCAGGACCCACAGATAAGGCAGGAGGTGAG
				</data>
				<hit pos="88" gap="87" motif="motif_3" pvalue="4.4e-05" strand="reverse" match="+++++++"/>
			</seg>
		</sequence>
		<sequence id="seq_1_133" db="db_1" num="133" name="jur_133" comment="" length="606">
			<score strand="both" combined_pvalue="4.05e-03" evalue="0.61"/>
			<seg start="76">
				<data>
TTTCTACACAGGGACTCCGAAATTCTACATGGGTAGCAGTCAATTTCAACCCCACAAGAAGATGTAGGTGGGGAG
				</data>
				<hit pos="143" gap="142" motif="motif_4" pvalue="4.4e-05" strand="forward" match="+++++++"/>
			</seg>
		</sequence>
	</sequences>
	<runtime cycles="17370" seconds="0.017"/>
</mast>
